### ISSUE TITLE
Ambari Installation Failure on HDP Sandbox 2.2.4 - Spring XD Shell Install 

### ISSUE THREAD

**Issue by willschipp** [spring-projects/spring-xd-ambari#1]
encountered the following error when installing on Hortonwork SandBox 2.2.4.  Looks like a problem with the kerberos python script?

_stderr_

```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 39, in <module>
    SpringXdShell().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 214, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 31, in install
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 34, in configure
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/params.py", line 135, in <module>
    kinit_path_local = functions.get_kinit_path(["/usr/bin", "/usr/kerberos/bin", "/usr/sbin"])
TypeError: get_kinit_path() takes no arguments (1 given)
```

_stdout_

```
2015-06-15 07:56:30,519 - u"Group['hadoop']" {'ignore_failures': False}
2015-06-15 07:56:30,520 - Modifying group hadoop
2015-06-15 07:56:30,577 - u"Group['users']" {'ignore_failures': False}
2015-06-15 07:56:30,577 - Modifying group users
2015-06-15 07:56:30,625 - u"Group['spark']" {'ignore_failures': False}
2015-06-15 07:56:30,625 - Modifying group spark
2015-06-15 07:56:30,670 - u"User['oozie']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-06-15 07:56:30,671 - Modifying user oozie
2015-06-15 07:56:30,718 - u"User['hive']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:30,719 - Modifying user hive
2015-06-15 07:56:30,765 - u"User['ambari-qa']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-06-15 07:56:30,766 - Modifying user ambari-qa
2015-06-15 07:56:30,813 - u"User['spring-xd']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:30,814 - Modifying user spring-xd
2015-06-15 07:56:30,864 - u"User['flume']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:30,865 - Modifying user flume
2015-06-15 07:56:30,910 - u"User['hdfs']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:30,911 - Modifying user hdfs
2015-06-15 07:56:30,960 - u"User['storm']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:30,960 - Modifying user storm
2015-06-15 07:56:31,006 - u"User['spark']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,006 - Modifying user spark
2015-06-15 07:56:31,051 - u"User['mapred']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,052 - Modifying user mapred
2015-06-15 07:56:31,100 - u"User['hbase']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,104 - Modifying user hbase
2015-06-15 07:56:31,149 - u"User['tez']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-06-15 07:56:31,150 - Modifying user tez
2015-06-15 07:56:31,195 - u"User['zookeeper']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,196 - Modifying user zookeeper
2015-06-15 07:56:31,246 - u"User['kafka']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,247 - Modifying user kafka
2015-06-15 07:56:31,294 - u"User['falcon']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,294 - Modifying user falcon
2015-06-15 07:56:31,342 - u"User['sqoop']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,342 - Modifying user sqoop
2015-06-15 07:56:31,387 - u"User['yarn']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,387 - Modifying user yarn
2015-06-15 07:56:31,435 - u"User['hcat']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,436 - Modifying user hcat
2015-06-15 07:56:31,481 - u"User['ams']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-06-15 07:56:31,482 - Modifying user ams
2015-06-15 07:56:31,529 - u"File['/var/lib/ambari-agent/data/tmp/changeUid.sh']" {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2015-06-15 07:56:31,833 - u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa']" {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2015-06-15 07:56:31,878 - Skipping u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa']" due to not_if
2015-06-15 07:56:31,878 - u"Directory['/hadoop/hbase']" {'owner': 'hbase', 'recursive': True, 'mode': 0775, 'cd_access': 'a'}
2015-06-15 07:56:32,229 - u"File['/var/lib/ambari-agent/data/tmp/changeUid.sh']" {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2015-06-15 07:56:32,528 - u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/hadoop/hbase']" {'not_if': '(test $(id -u hbase) -gt 1000) || (false)'}
2015-06-15 07:56:32,573 - Skipping u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/hadoop/hbase']" due to not_if
2015-06-15 07:56:32,574 - u"Group['hdfs']" {'ignore_failures': False}
2015-06-15 07:56:32,574 - Modifying group hdfs
2015-06-15 07:56:32,619 - u"User['hdfs']" {'ignore_failures': False, 'groups': [u'hadoop', 'hadoop', 'hdfs', u'hdfs']}
2015-06-15 07:56:32,620 - Modifying user hdfs
2015-06-15 07:56:32,665 - u"Directory['/etc/hadoop']" {'mode': 0755}
2015-06-15 07:56:32,820 - u"Directory['/etc/hadoop/conf.empty']" {'owner': 'root', 'group': 'hadoop', 'recursive': True}
2015-06-15 07:56:32,974 - u"Link['/etc/hadoop/conf']" {'not_if': 'ls /etc/hadoop/conf', 'to': '/etc/hadoop/conf.empty'}
2015-06-15 07:56:33,021 - Skipping u"Link['/etc/hadoop/conf']" due to not_if
2015-06-15 07:56:33,030 - u"File['/etc/hadoop/conf/hadoop-env.sh']" {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2015-06-15 07:56:33,294 - u"Repository['HDP-2.2']" {'base_url': 'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.2.4.2/', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP', 'mirror_list': None}
2015-06-15 07:56:33,302 - u"File['/etc/yum.repos.d/HDP.repo']" {'content': Template('repo_suse_rhel.j2')}
2015-06-15 07:56:33,560 - u"Repository['HDP-UTILS-1.1.0.20']" {'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2015-06-15 07:56:33,564 - u"File['/etc/yum.repos.d/HDP-UTILS.repo']" {'content': Template('repo_suse_rhel.j2')}
2015-06-15 07:56:33,806 - u"Package['unzip']" {}
2015-06-15 07:56:34,335 - Skipping installing existent package unzip
2015-06-15 07:56:34,335 - u"Package['curl']" {}
2015-06-15 07:56:34,783 - Skipping installing existent package curl
2015-06-15 07:56:34,786 - u"Package['hdp-select']" {}
2015-06-15 07:56:35,195 - Skipping installing existent package hdp-select
2015-06-15 07:56:35,359 - u"Package['spring-xd']" {}
2015-06-15 07:56:35,778 - Skipping installing existent package spring-xd
2015-06-15 07:56:35,785 - call['/usr/bin/hdp-select versions > /tmp/tmpLoP_yh'] {}
```

**Comment by jvalkeal** [comment]
Looks like `/usr/lib/ambari-server/lib/resource_management/libraries/functions/get_kinit_path.py` is different with Ambari 2.0.0 this vm is based on. Ambari 1.7.0/2.0.1 has `get_kinit_path` function which takes an argument. Not sure if we even want to fix this.

**Comment by trisberg** [comment]
Let's wait for the HDP 2.2.6 Sandbox to come out to see if it works there

**Comment by willschipp** [comment]
when trying to upgrade ambari on the sandbox (as per https://cwiki.apache.org/confluence/display/AMBARI/Install+Ambari+2.0.1+from+Public+Repositories) I run into this known issue (https://issues.apache.org/jira/browse/AMBARI-11000)

so +1 for trisberg's comment

**Comment by jvalkeal** [comment]
right, closing this. re-open if similar problems cause trouble.
