### ISSUE TITLE
Ambari Installation Failure on HDP Sandbox 2.3 - Spring XD Shell Install

### ISSUE THREAD

**Issue by jagatsingh** [spring-projects/spring-xd-ambari#5]
HDP 2.3 is coming. time to see its requirements

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 39, in <module>
    SpringXdShell().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 216, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 31, in install
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 34, in configure
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/params.py", line 151, in <module>
    HdfsDirectory,
NameError: name 'HdfsDirectory' is not defined

Directory permissions

drwxrwxrwx   - hdfs   hdfs            0 2015-07-09 04:28 /user

[root@sandbox ~]# hadoop fs -ls -R /tmp/hadoop-yarn
drwxrwxrwx   - yarn hdfs          0 2015-07-12 05:47 /tmp/hadoop-yarn/staging
drwxrwxrwx   - yarn hdfs          0 2015-07-12 05:47 /tmp/hadoop-yarn/staging/history

**Comment by trisberg** [comment]
The HDP 2.3 Technical Preview Sandbox uses Ambari 2.1(Build 781) according to the release notes. Our Ambari support is for 1.7.0, 1.7.1 and 2.0.1. Looks like we need to make some changes to accommodate Ambari 2.1 in a future release.

**Comment by tzolov** [comment]
#11 provides a fix for supporting HDP2.3 and Ambari 2.1

**Comment by getstek** [comment]
I get this when trying to build on 2.2 stack on Ambari:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 39, in <module>
    SpringXdShell().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 218, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 31, in install
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/springxd_shell.py", line 34, in configure
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/SPRINGXD/package/scripts/params.py", line 151, in <module>
    HdfsDirectory,
NameError: name 'HdfsDirectory' is not defined

Following the install instructions on the Github page. What am I missing?

**Comment by trisberg** [comment]
What version of Ambari? Our Ambari support works with 1.7.0, 1.7.1 and 2.0.1.
